"""
New ChatCompletionResponse that aligns with the latest OpenAI API.
Based on openai.types.chat.chat_completion.ChatCompletion class.
"""

from typing import Literal

from pydantic import BaseModel, Field

from .usage import SoUsage


class FunctionCall(BaseModel):
    """Function call information."""

    arguments: str = Field(
        ...,
        description="The arguments to call the function with, as generated by the model in JSON format.",
    )
    name: str = Field(..., description="The name of the function to call.")


class ChatCompletionMessageToolCall(BaseModel):
    """Tool call made by the model."""

    id: str
    """The ID of the tool call."""

    function: FunctionCall
    """The function that the model called."""

    type: Literal["function"]
    """The type of the tool. Currently, only `function` is supported."""


class ChatCompletionMessage(BaseModel):
    """A chat completion message generated by the model."""

    content: str | None = None
    """The contents of the message."""

    refusal: str | None = None
    """The refusal message generated by the model."""

    role: Literal["assistant"]
    """The role of the author of this message."""

    tool_calls: list[ChatCompletionMessageToolCall] | None = None
    """The tool calls generated by the model, such as function calls."""

    reasoning: str | None = None
    """Reasoning generated by the model."""

    reasoning_details: list[dict] | None = None
    """Detailed reasoning information from the model."""


class Choice(BaseModel):
    """A chat completion choice."""

    finish_reason: Literal[
        "stop", "length", "tool_calls", "content_filter", "function_call"
    ]
    """The reason the model stopped generating tokens."""

    index: int
    """The index of the choice in the list of choices."""

    message: ChatCompletionMessage
    """A chat completion message generated by the model."""


class ChatCompletionResponse(BaseModel):
    """
    Chat completion response that aligns with the latest OpenAI API.
    Based on openai.types.chat.chat_completion.ChatCompletion class.
    """

    id: str
    """A unique identifier for the chat completion."""

    choices: list[Choice]
    """A list of chat completion choices. Can be more than one if `n` is greater than 1."""

    created: int
    """The Unix timestamp (in seconds) of when the chat completion was created."""

    model: str
    """The model used for the chat completion."""

    object: Literal["chat.completion"] = "chat.completion"
    """The object type, which is always `chat.completion`."""

    usage: SoUsage | None = None
    """Usage statistics for the completion request."""

    session_id: str | None = None
