from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

# =============================================================================
# Usage
# =============================================================================


class CompletionUsage(BaseModel):
    """Usage statistics for the completion request."""

    completion_tokens: int = Field(description="Number of tokens in the generated completion.")
    prompt_tokens: int = Field(description="Number of tokens in the prompt.")
    total_tokens: int = Field(description="Total number of tokens used in the request (prompt + completion).")

    model_config = ConfigDict(extra="forbid")


# =============================================================================
# Logprobs
# =============================================================================


class TopLogprob(BaseModel):
    """Top logprob entry."""

    token: str = Field(description="The token.")
    bytes: list[int] | None = Field(
        default=None,
        description="A list of integers representing the UTF-8 bytes representation of the token.",
    )
    logprob: float = Field(
        description="The log probability of this token, if it is within the top 20 most likely tokens."
    )

    model_config = ConfigDict(extra="forbid")


class TokenLogprob(BaseModel):
    """Token log probability information."""

    token: str = Field(description="The token.")
    bytes: list[int] | None = Field(
        default=None,
        description="A list of integers representing the UTF-8 bytes representation of the token.",
    )
    logprob: float = Field(
        description="The log probability of this token, if it is within the top 20 most likely tokens."
    )
    top_logprobs: list[TopLogprob] = Field(
        description="List of the most likely tokens and their log probability, at this token position."
    )

    model_config = ConfigDict(extra="forbid")


class ChoiceLogprobs(BaseModel):
    """Log probability information for a choice."""

    content: list[TokenLogprob] | None = Field(
        default=None,
        description="A list of message content tokens with log probability information.",
    )
    refusal: list[TokenLogprob] | None = Field(
        default=None,
        description="A list of message refusal tokens with log probability information.",
    )

    model_config = ConfigDict(extra="forbid")


# =============================================================================
# Tool Calls
# =============================================================================


class ToolCallFunction(BaseModel):
    """Function details in tool call."""

    arguments: str = Field(
        description="The arguments to call the function with, as generated by the model in JSON format."
    )
    name: str = Field(description="The name of the function to call.")

    model_config = ConfigDict(extra="forbid")


class ResponseToolCall(BaseModel):
    """Tool call in assistant message."""

    id: str = Field(description="The ID of the tool call.")
    type: Literal["function"] = Field(description="The type of the tool. Currently, only 'function' is supported.")
    function: ToolCallFunction = Field(description="The function that the model called.")

    model_config = ConfigDict(extra="forbid")


# =============================================================================
# Message
# =============================================================================


class FunctionCallResult(BaseModel):
    """Function call result (deprecated)."""

    arguments: str = Field(
        description="The arguments to call the function with, as generated by the model in JSON format."
    )
    name: str = Field(description="The name of the function to call.")

    model_config = ConfigDict(extra="forbid")


class AnnotationUrlCitation(BaseModel):
    """URL citation annotation."""

    end_index: int = Field(description="The index of the last character of the URL citation in the message.")
    start_index: int = Field(description="The index of the first character of the URL citation in the message.")
    title: str = Field(description="The title of the web resource.")
    url: str = Field(description="The URL of the web resource.")

    model_config = ConfigDict(extra="forbid")


class Annotation(BaseModel):
    """Annotation in message."""

    type: Literal["url_citation"] = Field(description="The type of the URL citation. Always 'url_citation'.")
    url_citation: AnnotationUrlCitation = Field(description="A URL citation when using web search.")

    model_config = ConfigDict(extra="forbid")


class AudioResponse(BaseModel):
    """Audio response from the model."""

    id: str = Field(description="Unique identifier for this audio response.")
    data: str = Field(
        description="Base64 encoded audio bytes generated by the model, in the format specified in the request."
    )
    expires_at: int = Field(
        description="The Unix timestamp (in seconds) for when this audio response will no longer be accessible on the server."
    )
    transcript: str = Field(description="Transcript of the audio generated by the model.")

    model_config = ConfigDict(extra="forbid")


class ResponseMessage(BaseModel):
    """A chat completion message generated by the model."""

    role: Literal["assistant"] = Field(description="The role of the author of this message.")
    content: str | None = Field(default=None, description="The contents of the message.")
    refusal: str | None = Field(default=None, description="The refusal message generated by the model.")
    annotations: list[Annotation] | None = Field(
        default=None,
        description="Annotations for the message, when applicable, as when using the web search tool.",
    )
    audio: AudioResponse | None = Field(
        default=None,
        description="If the audio output modality is requested, this object contains data about the audio response from the model.",
    )
    function_call: FunctionCallResult | None = Field(
        default=None,
        description="Deprecated and replaced by tool_calls. The name and arguments of a function that should be called.",
    )
    tool_calls: list[ResponseToolCall] | None = Field(
        default=None,
        description="The tool calls generated by the model, such as function calls.",
    )

    model_config = ConfigDict(extra="forbid")


# =============================================================================
# Choice
# =============================================================================


class Choice(BaseModel):
    """A chat completion choice."""

    finish_reason: Literal["stop", "length", "tool_calls", "content_filter", "function_call"] = Field(
        description="The reason the model stopped generating tokens. 'stop' for natural stop, 'length' for max tokens, 'tool_calls' for tool call, 'content_filter' for content filter, 'function_call' (deprecated) for function call."
    )
    index: int = Field(description="The index of the choice in the list of choices.")
    message: ResponseMessage = Field(description="A chat completion message generated by the model.")
    logprobs: ChoiceLogprobs | None = Field(default=None, description="Log probability information for the choice.")

    model_config = ConfigDict(extra="forbid")


# =============================================================================
# Main Response Class
# =============================================================================


class ChatCompletionResponse(BaseModel):
    """
    OpenAI Chat Completion response.

    This is a Pydantic model representation of the OpenAI chat completion response.
    """

    id: str = Field(description="A unique identifier for the chat completion.")
    choices: list[Choice] = Field(
        description="A list of chat completion choices. Can be more than one if 'n' is greater than 1."
    )
    created: int = Field(description="The Unix timestamp (in seconds) of when the chat completion was created.")
    model: str = Field(description="The model used for the chat completion.")
    object: Literal["chat.completion"] = Field(description="The object type, which is always 'chat.completion'.")
    usage: CompletionUsage | None = Field(default=None, description="Usage statistics for the completion request.")
    session_id: str | None = Field(
        default=None, description="The session ID associated with this chat completion, if applicable."
    )

    model_config = ConfigDict(extra="forbid")
